// Static list of NSE-listed equities for autocomplete search.
// Symbol is the bare NSE symbol (without .NS suffix).
export interface NseSymbol {
  symbol: string;
  name: string;
  sector: string;
}

export const NSE_SYMBOLS: NseSymbol[] = [
  // Nifty 50
  { symbol: "RELIANCE", name: "Reliance Industries Limited", sector: "Energy" },
  { symbol: "TCS", name: "Tata Consultancy Services", sector: "IT" },
  { symbol: "HDFCBANK", name: "HDFC Bank Limited", sector: "Financial Services" },
  { symbol: "ICICIBANK", name: "ICICI Bank Limited", sector: "Financial Services" },
  { symbol: "INFY", name: "Infosys Limited", sector: "IT" },
  { symbol: "HINDUNILVR", name: "Hindustan Unilever Limited", sector: "FMCG" },
  { symbol: "SBIN", name: "State Bank of India", sector: "Financial Services" },
  { symbol: "BAJFINANCE", name: "Bajaj Finance Limited", sector: "Financial Services" },
  { symbol: "BHARTIARTL", name: "Bharti Airtel Limited", sector: "Telecom" },
  { symbol: "KOTAKBANK", name: "Kotak Mahindra Bank", sector: "Financial Services" },
  { symbol: "LT", name: "Larsen & Toubro Limited", sector: "Infrastructure" },
  { symbol: "AXISBANK", name: "Axis Bank Limited", sector: "Financial Services" },
  { symbol: "ASIANPAINT", name: "Asian Paints Limited", sector: "Consumer" },
  { symbol: "HCLTECH", name: "HCL Technologies Limited", sector: "IT" },
  { symbol: "ITC", name: "ITC Limited", sector: "FMCG" },
  { symbol: "MARUTI", name: "Maruti Suzuki India Limited", sector: "Automobile" },
  { symbol: "WIPRO", name: "Wipro Limited", sector: "IT" },
  { symbol: "NTPC", name: "NTPC Limited", sector: "Energy" },
  { symbol: "POWERGRID", name: "Power Grid Corporation", sector: "Energy" },
  { symbol: "ONGC", name: "Oil and Natural Gas Corporation", sector: "Energy" },
  { symbol: "SUNPHARMA", name: "Sun Pharmaceutical Industries", sector: "Pharma" },
  { symbol: "TATAMOTORS", name: "Tata Motors Limited", sector: "Automobile" },
  { symbol: "TATASTEEL", name: "Tata Steel Limited", sector: "Metals" },
  { symbol: "JSWSTEEL", name: "JSW Steel Limited", sector: "Metals" },
  { symbol: "HINDALCO", name: "Hindalco Industries Limited", sector: "Metals" },
  { symbol: "M&M", name: "Mahindra & Mahindra Limited", sector: "Automobile" },
  { symbol: "TITAN", name: "Titan Company Limited", sector: "Consumer" },
  { symbol: "ULTRACEMCO", name: "UltraTech Cement Limited", sector: "Cement" },
  { symbol: "COALINDIA", name: "Coal India Limited", sector: "Energy" },
  { symbol: "DIVISLAB", name: "Divi's Laboratories", sector: "Pharma" },
  { symbol: "DRREDDY", name: "Dr. Reddy's Laboratories", sector: "Pharma" },
  { symbol: "BAJAJ-AUTO", name: "Bajaj Auto Limited", sector: "Automobile" },
  { symbol: "BAJAJFINSV", name: "Bajaj Finserv Limited", sector: "Financial Services" },
  { symbol: "EICHERMOT", name: "Eicher Motors Limited", sector: "Automobile" },
  { symbol: "GRASIM", name: "Grasim Industries Limited", sector: "Cement" },
  { symbol: "HDFCLIFE", name: "HDFC Life Insurance", sector: "Financial Services" },
  { symbol: "HEROMOTOCO", name: "Hero MotoCorp Limited", sector: "Automobile" },
  { symbol: "INDUSINDBK", name: "IndusInd Bank Limited", sector: "Financial Services" },
  { symbol: "NESTLEIND", name: "Nestle India Limited", sector: "FMCG" },
  { symbol: "SBILIFE", name: "SBI Life Insurance", sector: "Financial Services" },
  { symbol: "TATACONSUM", name: "Tata Consumer Products", sector: "FMCG" },
  { symbol: "TECHM", name: "Tech Mahindra Limited", sector: "IT" },
  { symbol: "APOLLOHOSP", name: "Apollo Hospitals Enterprise", sector: "Pharma" },
  { symbol: "ADANIPORTS", name: "Adani Ports & SEZ", sector: "Infrastructure" },
  { symbol: "ADANIENT", name: "Adani Enterprises Limited", sector: "Diversified" },
  { symbol: "BPCL", name: "Bharat Petroleum Corporation", sector: "Energy" },
  { symbol: "CIPLA", name: "Cipla Limited", sector: "Pharma" },
  { symbol: "UPL", name: "UPL Limited", sector: "Chemicals" },
  { symbol: "BRITANNIA", name: "Britannia Industries Limited", sector: "FMCG" },
  { symbol: "ICICIGI", name: "ICICI Lombard General Insurance", sector: "Financial Services" },
  // Nifty Next 50
  { symbol: "ABB", name: "ABB India Limited", sector: "Infrastructure" },
  { symbol: "ADANIGREEN", name: "Adani Green Energy", sector: "Energy" },
  { symbol: "AMBUJACEM", name: "Ambuja Cements Limited", sector: "Cement" },
  { symbol: "AUROPHARMA", name: "Aurobindo Pharma Limited", sector: "Pharma" },
  { symbol: "BANKBARODA", name: "Bank of Baroda", sector: "Financial Services" },
  { symbol: "BERGEPAINT", name: "Berger Paints India", sector: "Consumer" },
  { symbol: "BEL", name: "Bharat Electronics Limited", sector: "Defense" },
  { symbol: "BOSCHLTD", name: "Bosch Limited", sector: "Automobile" },
  { symbol: "CANBK", name: "Canara Bank", sector: "Financial Services" },
  { symbol: "CHOLAFIN", name: "Cholamandalam Investment", sector: "Financial Services" },
  { symbol: "COLPAL", name: "Colgate-Palmolive India", sector: "FMCG" },
  { symbol: "CONCOR", name: "Container Corporation of India", sector: "Logistics" },
  { symbol: "DABUR", name: "Dabur India Limited", sector: "FMCG" },
  { symbol: "DLF", name: "DLF Limited", sector: "Real Estate" },
  { symbol: "GODREJCP", name: "Godrej Consumer Products", sector: "FMCG" },
  { symbol: "HAVELLS", name: "Havells India Limited", sector: "Consumer" },
  { symbol: "HINDZINC", name: "Hindustan Zinc Limited", sector: "Metals" },
  { symbol: "INDHOTEL", name: "Indian Hotels Company", sector: "Consumer" },
  { symbol: "IOC", name: "Indian Oil Corporation", sector: "Energy" },
  { symbol: "IGL", name: "Indraprastha Gas Limited", sector: "Energy" },
  { symbol: "IRCTC", name: "Indian Railway Catering & Tourism", sector: "Logistics" },
  { symbol: "JINDALSTEL", name: "Jindal Steel & Power", sector: "Metals" },
  { symbol: "LICI", name: "Life Insurance Corporation of India", sector: "Financial Services" },
  { symbol: "LUPIN", name: "Lupin Limited", sector: "Pharma" },
  { symbol: "MARICO", name: "Marico Limited", sector: "FMCG" },
  { symbol: "MUTHOOTFIN", name: "Muthoot Finance Limited", sector: "Financial Services" },
  { symbol: "NAUKRI", name: "Info Edge (India) Limited", sector: "IT" },
  { symbol: "NMDC", name: "NMDC Limited", sector: "Metals" },
  { symbol: "OFSS", name: "Oracle Financial Services", sector: "IT" },
  { symbol: "PIIND", name: "PI Industries Limited", sector: "Chemicals" },
  { symbol: "PIDILITIND", name: "Pidilite Industries Limited", sector: "Consumer" },
  { symbol: "PNB", name: "Punjab National Bank", sector: "Financial Services" },
  { symbol: "RECLTD", name: "REC Limited", sector: "Financial Services" },
  { symbol: "SAIL", name: "Steel Authority of India", sector: "Metals" },
  { symbol: "SIEMENS", name: "Siemens Limited", sector: "Infrastructure" },
  { symbol: "SRF", name: "SRF Limited", sector: "Chemicals" },
  { symbol: "TATAPOWER", name: "Tata Power Company", sector: "Energy" },
  { symbol: "TORNTPHARM", name: "Torrent Pharmaceuticals", sector: "Pharma" },
  { symbol: "TRENT", name: "Trent Limited", sector: "Consumer" },
  { symbol: "VEDL", name: "Vedanta Limited", sector: "Metals" },
  { symbol: "VOLTAS", name: "Voltas Limited", sector: "Consumer" },
  { symbol: "ZOMATO", name: "Zomato Limited", sector: "Consumer" },
  { symbol: "ZYDUSLIFE", name: "Zydus Lifesciences Limited", sector: "Pharma" },
  { symbol: "IDFCFIRSTB", name: "IDFC First Bank Limited", sector: "Financial Services" },
  { symbol: "HAL", name: "Hindustan Aeronautics Limited", sector: "Defense" },
  { symbol: "BEML", name: "Bharat Earth Movers Limited", sector: "Defense" },
  { symbol: "ATGL", name: "Adani Total Gas Limited", sector: "Energy" },
  { symbol: "MGL", name: "Mahanagar Gas Limited", sector: "Energy" },
  { symbol: "RENUKA", name: "Renuka Sugars Limited", sector: "Commodities" },
  { symbol: "INDUSTOWER", name: "Indus Towers Limited", sector: "Telecom" },
  // Additional large-cap NSE stocks
  { symbol: "LTIM", name: "LTIMindtree Limited", sector: "IT" },
  { symbol: "MPHASIS", name: "Mphasis Limited", sector: "IT" },
  { symbol: "PERSISTENT", name: "Persistent Systems Limited", sector: "IT" },
  { symbol: "COFORGE", name: "Coforge Limited", sector: "IT" },
  { symbol: "LTTS", name: "L&T Technology Services", sector: "IT" },
  { symbol: "KPITTECH", name: "KPIT Technologies Limited", sector: "IT" },
  { symbol: "RBLBANK", name: "RBL Bank Limited", sector: "Financial Services" },
  { symbol: "FEDERALBNK", name: "Federal Bank Limited", sector: "Financial Services" },
  { symbol: "YESBANK", name: "Yes Bank Limited", sector: "Financial Services" },
  { symbol: "BANDHANBNK", name: "Bandhan Bank Limited", sector: "Financial Services" },
  { symbol: "ABCAPITAL", name: "Aditya Birla Capital", sector: "Financial Services" },
  { symbol: "MANAPPURAM", name: "Manappuram Finance Limited", sector: "Financial Services" },
  { symbol: "LICHSGFIN", name: "LIC Housing Finance", sector: "Financial Services" },
  { symbol: "SRTRANSFIN", name: "Shriram Finance Limited", sector: "Financial Services" },
  { symbol: "BIOCON", name: "Biocon Limited", sector: "Pharma" },
  { symbol: "ALKEM", name: "Alkem Laboratories", sector: "Pharma" },
  { symbol: "IPCA", name: "Ipca Laboratories", sector: "Pharma" },
  { symbol: "GLENMARK", name: "Glenmark Pharmaceuticals", sector: "Pharma" },
  { symbol: "NATCO", name: "Natco Pharma Limited", sector: "Pharma" },
  { symbol: "STAR", name: "Star Health Insurance", sector: "Financial Services" },
  { symbol: "MAXHEALTH", name: "Max Healthcare Institute", sector: "Pharma" },
  { symbol: "FORTIS", name: "Fortis Healthcare Limited", sector: "Pharma" },
  { symbol: "ASHOKLEY", name: "Ashok Leyland Limited", sector: "Automobile" },
  { symbol: "TVSMOTOR", name: "TVS Motor Company", sector: "Automobile" },
  { symbol: "BHEL", name: "Bharat Heavy Electricals", sector: "Infrastructure" },
  { symbol: "CUMMINSIND", name: "Cummins India Limited", sector: "Infrastructure" },
  { symbol: "THERMAX", name: "Thermax Limited", sector: "Infrastructure" },
  { symbol: "POLYCAB", name: "Polycab India Limited", sector: "Consumer" },
  { symbol: "WHIRLPOOL", name: "Whirlpool of India", sector: "Consumer" },
  { symbol: "CROMPTON", name: "Crompton Greaves Consumer", sector: "Consumer" },
  { symbol: "DIXON", name: "Dixon Technologies", sector: "Consumer" },
  { symbol: "AMBER", name: "Amber Enterprises India", sector: "Consumer" },
  { symbol: "DMART", name: "Avenue Supermarts (DMart)", sector: "Consumer" },
  { symbol: "NYKAA", name: "FSN E-Commerce Ventures (Nykaa)", sector: "Consumer" },
  { symbol: "PAYTM", name: "One97 Communications (Paytm)", sector: "IT" },
  { symbol: "POLICYBZR", name: "PB Fintech (PolicyBazaar)", sector: "Financial Services" },
  { symbol: "CARTRADE", name: "CarTrade Tech Limited", sector: "Consumer" },
  { symbol: "GODREJPROP", name: "Godrej Properties Limited", sector: "Real Estate" },
  { symbol: "OBEROIRLTY", name: "Oberoi Realty Limited", sector: "Real Estate" },
  { symbol: "PRESTIGE", name: "Prestige Estates Projects", sector: "Real Estate" },
  { symbol: "SOBHA", name: "Sobha Limited", sector: "Real Estate" },
  { symbol: "GAIL", name: "GAIL (India) Limited", sector: "Energy" },
  { symbol: "PETRONET", name: "Petronet LNG Limited", sector: "Energy" },
  { symbol: "OIL", name: "Oil India Limited", sector: "Energy" },
  { symbol: "NHPC", name: "NHPC Limited", sector: "Energy" },
  { symbol: "CESC", name: "CESC Limited", sector: "Energy" },
  { symbol: "TORNTPOWER", name: "Torrent Power Limited", sector: "Energy" },
  { symbol: "RATNAMANI", name: "Ratnamani Metals & Tubes", sector: "Metals" },
  { symbol: "WELCORP", name: "Welspun Corp Limited", sector: "Metals" },
  { symbol: "SHYAMMETL", name: "Shyam Metalics and Energy", sector: "Metals" },
  { symbol: "APLAPOLLO", name: "APL Apollo Tubes", sector: "Metals" },
  { symbol: "RAMCOCEM", name: "Ramco Cements Limited", sector: "Cement" },
  { symbol: "JKCEMENT", name: "JK Cement Limited", sector: "Cement" },
  { symbol: "SHREECEM", name: "Shree Cement Limited", sector: "Cement" },
  { symbol: "DALBHARAT", name: "Dalmia Bharat Limited", sector: "Cement" },
  { symbol: "HEIDELBERG", name: "HeidelbergCement India", sector: "Cement" },
  { symbol: "ASTRAL", name: "Astral Limited", sector: "Chemicals" },
  { symbol: "DEEPAKNTR", name: "Deepak Nitrite Limited", sector: "Chemicals" },
  { symbol: "AARTI", name: "Aarti Industries Limited", sector: "Chemicals" },
  { symbol: "VINATI", name: "Vinati Organics Limited", sector: "Chemicals" },
  { symbol: "NAVINFLUOR", name: "Navin Fluorine International", sector: "Chemicals" },
  { symbol: "ROSSARI", name: "Rossari Biotech Limited", sector: "Chemicals" },
  { symbol: "CLEAN", name: "Clean Science and Technology", sector: "Chemicals" },
  { symbol: "TATACHEM", name: "Tata Chemicals Limited", sector: "Chemicals" },
  { symbol: "UFLEX", name: "UFLEX Limited", sector: "Chemicals" },
  { symbol: "BALRAMCHIN", name: "Balrampur Chini Mills", sector: "Commodities" },
  { symbol: "BSOFT", name: "BIRLASOFT Limited", sector: "IT" },
  { symbol: "HAPPSTMNDS", name: "Happiest Minds Technologies", sector: "IT" },
  { symbol: "TANLA", name: "Tanla Platforms Limited", sector: "IT" },
  { symbol: "INDIAMART", name: "IndiaMART InterMESH", sector: "IT" },
  { symbol: "JUSTDIAL", name: "Just Dial Limited", sector: "IT" },
  { symbol: "ZENSARTECH", name: "Zensar Technologies", sector: "IT" },
  { symbol: "MASTEK", name: "Mastek Limited", sector: "IT" },
  { symbol: "ECLERX", name: "eClerx Services Limited", sector: "IT" },
  { symbol: "MINDTREE", name: "Mindtree Limited (now LTIMindtree)", sector: "IT" },
  { symbol: "MCDOWELL-N", name: "United Spirits (McDowell's)", sector: "FMCG" },
  { symbol: "RADICO", name: "Radico Khaitan Limited", sector: "FMCG" },
  { symbol: "VBL", name: "Varun Beverages Limited", sector: "FMCG" },
  { symbol: "ZYDUSWELL", name: "Zydus Wellness Limited", sector: "FMCG" },
  { symbol: "BAJAJCON", name: "Bajaj Consumer Care", sector: "FMCG" },
  { symbol: "EMAMILTD", name: "Emami Limited", sector: "FMCG" },
  { symbol: "HATSUN", name: "Hatsun Agro Product", sector: "FMCG" },
  { symbol: "PGHH", name: "Procter & Gamble Hygiene", sector: "FMCG" },
  { symbol: "GILLETTE", name: "Gillette India Limited", sector: "FMCG" },
  { symbol: "GSPL", name: "Gujarat State Petronet", sector: "Energy" },
  { symbol: "AEGISLOG", name: "Aegis Logistics Limited", sector: "Logistics" },
  { symbol: "BLUEDART", name: "Blue Dart Express Limited", sector: "Logistics" },
  { symbol: "GATI", name: "Gati Limited", sector: "Logistics" },
  { symbol: "VRL", name: "VRL Logistics Limited", sector: "Logistics" },
  { symbol: "MAHLOG", name: "Mahindra Logistics Limited", sector: "Logistics" },
  { symbol: "EIHOTEL", name: "EIH Limited (Oberoi Hotels)", sector: "Consumer" },
  { symbol: "LEMON", name: "Lemon Tree Hotels", sector: "Consumer" },
  { symbol: "CHALET", name: "Chalet Hotels Limited", sector: "Consumer" },
  { symbol: "PCJEWELLER", name: "PC Jeweller Limited", sector: "Consumer" },
  { symbol: "SENCO", name: "Senco Gold Limited", sector: "Consumer" },
  { symbol: "RAYMOND", name: "Raymond Limited", sector: "Consumer" },
  { symbol: "PAGEIND", name: "Page Industries Limited", sector: "Consumer" },
  { symbol: "KPRMILL", name: "KPR Mill Limited", sector: "Consumer" },
  { symbol: "DCAL", name: "Dishman Carbogen Amcis", sector: "Pharma" },
  { symbol: "GRANULES", name: "Granules India Limited", sector: "Pharma" },
  { symbol: "AJANTPHARM", name: "Ajanta Pharma Limited", sector: "Pharma" },
  { symbol: "SUDARSCHEM", name: "Sudarshan Chemical", sector: "Chemicals" },

  // ── Global Macro (Forex & Commodities) ──────────────────────────────────
  { symbol: "USDINR=X", name: "USD/INR (US Dollar / Indian Rupee)", sector: "Currency" },
  { symbol: "GBPINR=X", name: "GBP/INR (British Pound / Indian Rupee)", sector: "Currency" },
  { symbol: "GC=F", name: "GOLD (Global Gold Future)", sector: "Commodities" },
  { symbol: "CL=F", name: "CRUDE OIL (Crude Oil Future)", sector: "Commodities" },
  { symbol: "SI=F", name: "SILVER (Global Silver Future)", sector: "Commodities" },
];
